import { SupabaseArticle } from './types';

export const MOCK_SUPABASE_DATA: SupabaseArticle[] = [
    {
        "id": "e2298642-4228-41d6-9a43-653919c0b561",
        "article_key": "lions-superbowl-window",
        "language_code": "de",
        "title": "Das Fenster zur Unsterblichkeit",
        "subtitle": "Die Lions jagen den Super-Bowl-Traum",
        "author": "BigSlikTobi",
        "published_at": "2025-12-05",
        "hero_image_url": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_images/2025_12_05_LionsSB16_9.png",
        "audio_file": "",
        "video_file": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_videos/lionsSB_teaser.mp4",
        "sections": {
            "section_1": "## Keine Tränen, nur Entschlossenheit\n### Nach einer bitteren Playoff-Niederlage weigern sich die Lions, ihre Super-Bowl-Träume aufzugeben.\n\nAls die letzten Sekunden im NFC Championship Game vor zwei Saisons verstrichen, stand Aidan Hutchinson, Defensive End der Detroit Lions, mit dem Helm in der Hand an der Seitenlinie und weigerte sich, auch nur eine Träne zu vergießen. Die Lions waren nur eine halbe Football-Partie von der Super-Bowl-Teilnahme entfernt gewesen, nur um mitzuerleben, wie ihre Führung in einem niederschmetternden Zusammenbruch in der zweiten Halbzeit dahinschmolz. Im stillen Umkleideraum sagte Hutchinson öffentlich nur wenig. Doch Tage später veröffentlichte er eine Botschaft, die die Stimmung in Detroit einfing: „In Detroit werdet ihr keine Tränen finden. Wenn ihr Ausreden wollt, werdet ihr sie nicht aus Ford Field hören … So hart die heutige Niederlage auch war, sie ist keine Definition der Kultur der Detroit Lions. Sie ist ein Beweis dafür, wie weit wir gekommen sind und wie weit wir noch gehen können“, erklärte der Lokalmatador und schwor, dass der Rückschlag ihren Hunger nur noch weiter anfachen würde. Jetzt, zu Beginn von Woche 13 der Saison 2025, brennt dieser Hunger heißer als je zuvor. Die Lions haben Herzschmerz in Hoffnung verwandelt, entschlossen, eine Meisterschaftschance zu ergreifen, die in Detroit einst unvorstellbar schien.",
            "section_2": "## High-Octane-Offense befeuert Detroits Angriff\n### Jared Goff und ein ausgewogenes Arsenal haben die Lions zu einem der explosivsten Offensivteams der Liga gemacht.\n\nNach diesem Playoff-Herzschmerz setzten die Lions voll auf ihre Offensive, um sicherzustellen, dass sie wieder im Kampf dabei sein würden. Quarterback Jared Goff, einst von den Rams aussortiert, hat sich in Detroits hochkarätiger Offensive zu einem selbstbewussten Anführer entwickelt. Umgeben von einem jungen Arsenal an Playmakern erzielte Goff in der letzten Saison eine Karrierebestleistung in puncto Effizienz, reduzierte Fehler und glänzte sogar, wenn die Gegner Druck machten. Die Lions waren das erste Team in der NFL-Geschichte, bei dem zwei Running Backs (der dynamische Rookie Jahmyr Gibbs und der bullige Veteran David Montgomery) und zwei Wide Receiver (Pro Bowler Amon-Ra St. Brown und der schnelle Jameson Williams) jeweils über 1.000 Yards Raumgewinn in derselben Saison erzielten. Fügt man den aufstrebenden Star-Tight-End Sam LaPorta hinzu, wird klar, warum Detroits Offensive zu den explosivsten der Liga gehört. Selbst nach dem Abgang des beliebten Offensive Coordinators Ben Johnson nach der letzten Saison entschied sich Coach Dan Campbell für Kontinuität und holte den erfahrenen Assistenten John Morton zurück, um das Schema und die Terminologie vertraut zu halten. Das Ergebnis? Eine Einheit, die immer noch Woche für Woche zu den besten der NFL in der Punkteproduktion zählt. Für Goff ist die Verwandlung in Detroit eine zutiefst persönliche Angelegenheit. „Seit ich hier bin, war es mein Ziel, dort zu stehen, wo wir jetzt stehen, und eine Chance zu haben, den Super Bowl zu gewinnen, ist ziemlich aufregend. Wir haben noch einen langen Weg vor uns“, sagte Goff und ordnete den jüngsten Erfolg des Teams realistisch ein. Dieses maßvolle Selbstvertrauen durchdringt eine Offensive, die glaubt, gegen jeden punkten zu können – ein Glaube, auf den sich die Lions stützen werden, wenn die Einsätze steigen.",
            "section_3": "## Eine Verteidigung mit Biss\n### Detroits einst geschmähte Verteidigung steigert sich, während Stars zurückkehren und ein Mantra der Hartnäckigkeit ihre Wiederauferstehung befeuern.\n\nDie Verteidigung war früher die Achillesferse der Lions, aber dieses Narrativ ändert sich mit aller Macht. Letzte Saison wurde Detroits Verteidigung von Verletzungen heimgesucht, 21 verschiedene Spieler landeten auf der Injured-Reserve-Liste, was sie 2024 zur vom Verletzungspech am stärksten gebeutelten Einheit der Liga machte. Trotz der Rückschläge hatte Koordinator Aaron Glenn eine bissige junge Truppe aufgebaut. Zur Saisonmitte gehörten sie zu den besten der NFL, bevor die Verletzungsmisere zuschlug. Dieses Jahr bringt einen Neuanfang unter dem neuen Defensive Coordinator Kelvin Sheppard und einen erneuerten Fokus auf Aggressivität und Grundlagen. Die Auswirkungen der Rückkehr ihrer gesunden Stars waren sofort spürbar. Edge Rusher Aidan Hutchinson, vollständig von einem Beinbruch erholt, hat seine dominante Form wiedergefunden. Er begann die letzte Saison mit 7,5 Sacks in nur fünf Spielen, mehr als jeder andere Verteidiger in der NFL in diesem Zeitraum. Jetzt wird er von aufstrebenden Playmakern wie Linebacker Jack Campbell und Safety Kerby Joseph flankiert, was Detroit eine jugendliche, schwärmende Verteidigung mit echtem Biss verleiht. Eine Leistung zu Beginn der Saison brachte den Aufstieg der Einheit auf den Punkt: An einem Montagabend in Baltimore jagte die Lions-Verteidigung Ravens-Quarterback Lamar Jackson über das ganze Feld und sackte ihn sieben Mal in einem Statement-Sieg, der die Ankunft von Detroits Verteidigung verkündete. Mit einem von Sheppard und den Veteranen eingeflößten Selbstbewusstsein geht diese Einheit nun in jedes Spiel mit der Absicht, die Speerspitze zu sein. Mit Hutchinson, der mit gutem Beispiel vorangeht, und so vielen zurückkehrenden Verstärkungen sieht die Verteidigung der Lions nicht mehr wie eine Schwachstelle aus, sondern wie ein Katalysator für einen Meisterschaftslauf.",
            "section_4": "## Geführt von Entschlossenheit: Der Campbell-Faktor\n### Cheftrainer Dan Campbell hat mit seinem Kulturwandel die Lions verwandelt, aber der Verlust seiner Top-Assistenten wird die Widerstandsfähigkeit Detroits auf die Probe stellen.\n\nVon dem Moment an, als Dan Campbell 2021 als Cheftrainer ankam und davon sprach, Kniescheiben abzubeißen, machte er eines klar: Seine Lions würden durch Härte und Herz definiert werden. In den letzten Saisons hat sich dieses Ethos durchgesetzt. Detroit entwickelte sich vom Liga-Fußabtreter zu einer Bilanz von 36-15 in den letzten drei Saisons, der viertbesten Bilanz in der NFL, und stieg an die Spitze der NFC North auf, angetrieben von einer Legion aufblühender junger Talente. „Sie haben eine legitime Kultur der Entschlossenheit und Härte etabliert“, bemerkte ein gegnerischer Scout und hob hervor, wie Campbells Team „jedes einzelne Jahr“ unter seiner Führung aufstieg. Die feurige, ansteckende Energie des Trainers hat eine Franchise galvanisiert, die früher das Schlimmste erwartete. Jetzt steht Campbell vielleicht vor seiner größten Prüfung als Anführer. Im vergangenen Offseason wurden beide seiner brillanten Koordinatoren zu Cheftrainern ernannt: Offensiv-Guru Ben Johnson nach Chicago und Defensiv-Chef Aaron Glenn zu den New York Jets. Ein solcher doppelter Aderlass ist fast beispiellos, und selbst einige NFL-Insider fragten sich, ob die überragenden Lions ohne diese Köpfe im Stab „abfallen“ könnten. Campbells Antwort war, der von ihm aufgebauten Kultur zu vertrauen: Er beförderte den 34-jährigen Linebackers-Coach Kelvin Sheppard zum Leiter der Verteidigung und holte den erfahrenen Assistenten John Morton zurück, um die Spielzüge in der Offensive zu callen. Sheppard war noch nie Koordinator auf diesem Niveau, während Morton für seine zweite Amtszeit als NFL Offensive Coordinator zurückkehrt, nachdem er 2017 bereits die Offensive der Jets geleitet hatte – ein Glücksspiel, das in der Liga für hochgezogene Augenbrauen sorgte. Aber innerhalb der Lions-Einrichtung herrscht der Glaube, dass Campbells Vision und das von ihm gelegte Fundament sie durch den Übergang tragen werden. Wie er seine Spieler oft daran erinnert, ändert sich der Standard in Detroit nicht, nur weil sich die Gesichter ändern.",
            "section_5": "## Jetzt oder nie? Das Fenster der Gelegenheit\n### Detroits Meisterschaftsfenster ist offen, und was als Nächstes kommt, wird das Vermächtnis einer leidgeprüften Franchise definieren.\n\nNach Jahrzehnten der Erfolglosigkeit ist das Fenster der Lions für eine Meisterschaft endlich offen, aber niemand weiß, wie lange. In der Super-Bowl-Ära hat Detroit nur ein einziges Playoff-Spiel gewonnen und die größte Bühne des Sports nie erreicht. Die Fans in Detroit haben Generationen von Enttäuschungen ertragen und auf ein Team wie dieses gewartet, an das sie glauben können. Deshalb tragen die 2025 Lions sowohl die Hoffnungen einer Stadt als auch das Gewicht der Erwartungen. Auf dem Papier ist die Gelegenheit da: Der Kader ist gespickt mit jungen Stars in ihrer Blütezeit, und das aus zwei aufeinanderfolgenden Playoff-Kampagnen gewonnene Selbstvertrauen hat einen neuen Standard gesetzt. Aber die NFL hat die Eigenart, Fenster im Handumdrehen zuzuschlagen. Rivalisierende Führungskräfte haben offen darüber spekuliert, ob Detroits Lauf bereits seinen Höhepunkt erreicht haben könnte, insbesondere nach dem Verlust seiner Schlüssel-Trainer. „Es ist immer noch ein gutes Team, versteht mich nicht falsch, aber das ist kein 14-2-Team mehr. Sie sehen für mich eher wie 10-7, 11-6 aus“, warnte ein gegnerischer GM und deutete an, dass der Spielraum für Fehler kleiner geworden ist. Dan Campbell braucht die Erinnerung nicht. Seine emotionale Warnung nach dem Spiel nach dem knappen Scheitern der Lions vor zwei Saisons hallt immer noch nach: „Ich habe den Jungs gesagt, das war vielleicht unsere einzige Chance … Und es wird doppelt so schwer sein, nächstes Jahr wieder an diesen Punkt zu gelangen.“ Seinen Worten treu, war die seitdem vergangene Saison in der Tat ein harter Kampf. Doch während die Lions auf ein hoffentlich anderes Ende zusteuern, wird die Geschichte bis zum Ende geschrieben wird, sie nehmen den Druck an, anstatt ihn zu fürchten. Dieses Team hat gelernt, sich durch Widrigkeiten zu kämpfen, ohne nach Ausreden zu suchen, genau wie Hutchinson es versprochen hatte. Ob die Lions dieses Fenster nutzen oder zusehen müssen, wie es sich schließt, ohne dass der große Triumph gelingt: Sie haben die NFL bereits jetzt verändert, indem sie Detroit wieder zu einem ernstzunehmenden Titelanwärter gemacht haben. Und sollte diese Geschichte tatsächlich in einer Super-Bowl-Feier gipfeln, wären all die Jahre des Herzschmerzes für die Lions und ihre treuen Anhänger mehr als wettgemacht."
        },
        "created_at": "2025-12-05T19:53:38.562577+00:00"
    },
    {
        "id": "ae891814-cb5a-43a4-b7d7-1264927c2f98",
        "article_key": "lions-superbowl-window",
        "language_code": "en",
        "title": "Roaring at the Brink",
        "subtitle": "Lions Chase a Super Bowl Dream",
        "author": "BigSlikTobi",
        "published_at": "2025-12-05",
        "hero_image_url": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_images/2025_12_05_LionsSB16_9.png",
        "audio_file": "",
      "video_file": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_videos/lionsSB_teaser.mp4",
        "sections": {
            "section_1": "## No Tears, Only Determination\n### After a gut-wrenching playoff defeat, the Lions refuse to let their Super Bowl dreams slip away. \n\nAs the final seconds ticked away in the NFC Championship Game two seasons ago, Detroit Lions defensive end Aidan Hutchinson stood on the sideline, helmet in hand, refusing to let any tears fall. The Lions had been just one half of football away from a Super Bowl berth, only to see their lead slip away in a crushing second-half collapse. In the quiet locker room afterward, Hutchinson said little publicly. But days later, he posted a message that captured the mood in Detroit: ‘You won’t find tears in Detroit. If you want excuses, you won’t hear them coming from Ford Field...  As hard as today’s loss was, it is not a definition of the Detroit Lions culture. It’s a testament to how far we have come and how far we can go,” the hometown star declared, vowing that the setback would only fuel their hunger. Now, as Week 13 of 2025 arrives, that hunger burns hotter than ever. The Lions have transformed heartbreak into hope, determined to seize a championship opportunity that once seemed unimaginable in Detroit.",
            "section_2": "## High-Octane Offense Ignites Detroit’s Charge\n### Jared Goff and a balanced arsenal have made the Lions one of the league’s most explosive offensive teams.\n\nAfter that playoff heartbreak, the Lions doubled down on their offense to ensure they’d be back in the fight. Quarterback Jared Goff, once cast off by the Rams, has flourished into a confident leader in Detroit’s high-octane attack. Surrounded by a young arsenal of playmakers, Goff posted career-best efficiency last season, cutting down on mistakes and even thriving when opponents brought pressure. The Lions became the first team in NFL history with two running backs (dynamic rookie Jahmyr Gibbs and bruising veteran David Montgomery) and two wide receivers (Pro Bowler Amon-Ra St. Brown and the speedy Jameson Williams) each gaining over 1,000 yards from scrimmage in the same year. Add in emerging star tight end Sam LaPorta, and it’s easy to see why Detroit’s offense has been among the league’s most explosive. Even with beloved offensive coordinator Ben Johnson departing after last season, coach Dan Campbell opted for continuity, rehiring veteran assistant John Morton to keep the scheme and terminology familiar. The result? A unit that still ranks near the top of the NFL in point production each week. For Goff, the transformation in Detroit is deeply personal. “Since I got here, it’s been a goal of mine to be where we’re standing right now and have a chance to win the Super Bowl is pretty exciting. We’ve got a long way to go,” Goff said, keeping the team’s recent success in perspective. That measured confidence trickles down through an offense that believes it can score on anyone, a belief the Lions will lean on as the stakes rise.",
            "section_3": "## A Defense with Bite\n### Detroit’s once-maligned defense is stepping up, with stars returning and a mantra of tenacity fueling its resurgence.\n\nDefense used to be the Lions’ sore spot, but that narrative is changing with a vengeance. Last season, Detroit’s defense was ravaged by injuries, 21 different players landed on injured reserve, making it the most snake-bit unit in the league in 2024. Despite the setbacks, coordinator Aaron Glenn had built a ferocious young group. By midseason they ranked among the NFL’s best before the injury bug hit. This year brings a fresh start under new defensive coordinator Kelvin Sheppard, and a renewed focus on aggressiveness and fundamentals. The impact of haveing their stars back healthy has been immediate. Edge rusher Aidan Hutchinson, fully recovered from a broken leg, has resumed his dominant form, he opened last season with 7.5 sacks in just five games, more than any defender in the NFL over that span. Now he’s flanked by emerging playmakers like linebacker Jack Campbell and safety Kerby Joseph, giving Detroit a youthful, swarming defense with real bite. One early-season performance encapsulated the unit’s rise: on a Monday night in Baltimore, the Lions defense chased Ravens quarterback Lamar Jackson all over the field, sacking him seven times in a statement win that announced Detroit’s defensive arrival. Playing with a swagger instilled by Sheppard and the veterans, this unit now approaches each game intent on being the tip of the spear. With Hutchinson leading by example and so many reinforcements returning, the Lions’ defense no longer looks like a liability, it looks like a catalyst for a championship run.",
            "section_4": "## Guided by Grit: The Campbell Factor\n### Head coach Dan Campbell’s culture change has transformed the Lions, but losing his top assistants will test Detroit’s resilience.\n\nFrom the moment Dan Campbell arrived as head coach in 2021 talking about biting off kneecaps, he made one thing clear: his Lions would be defined by toughness and heart. Over the past few seasons, that ethos has taken hold. Detroit went from league doormat to a 36-15 record over the past three seasons, the fourth-best mark in the NFL, rising to the top of the NFC North behind a legion of blossoming young talent. “They’ve installed a legitimate culture of grit and toughness,” observed one rival scout, noting how Campbell’s team “ascended every single year” under his guidance. The coach’s fiery, infectious energy has galvanized a franchise that used to expect the worst. Now Campbell faces perhaps his greatest test as a leader. This past offseason, both of his brilliant coordinators were hired away to head coaching jobs, offensive guru Ben Johnson to Chicago and defensive chief Aaron Glenn to the New York Jets. Such a dual brain drain is almost unheard of, and even some NFL insiders wondered if the overachieving Lions might “fall off” without those minds on staff. Campbell’s response was to trust the culture he built: he promoted 34-year-old linebackers coach Kelvin Sheppard to run the defense and brought back veteran assistant John Morton to call plays on offense. Sheppard has never been a coordinator at this level, while Morton returns for his second stint as an NFL offensive coordinator after previously running the Jets’ offense in 2017, a gamble that raised eyebrows around the league. But inside the Lions’ facility, there’s faith that Campbell’s vision and the foundation he’s laid will carry them through the transition. As he often reminds his players, the standard in Detroit doesn’t change just because the faces do.",
            "section_5": "## Now or Never? The Window of Opportunity\n### Detroit’s championship window is open and what comes next will define a long-suffering franchise’s legacy.\n\nAfter decades of futility, the Lions’ window for a championship is finally open but nobody knows for how long. In the Super Bowl era, Detroit has won only a single playoff game, never even reaching the sport’s biggest stage. Fans in Detroit have endured generations of disappointment, waiting for a team like this to believe in. That’s why the 2025 Lions carry both the hopes of a city and the weight of expectation. On paper, the opportunity is there: the roster is stacked with young stars in their prime, and the confidence gained from back-to-back playoff campaigns has set a new standard. But the NFL has a way of slamming windows shut in the blink of an eye. Rival executives have openly wondered if Detroit’s run might already have peaked, especially after the loss of its key coaches. “It’s still a good team, don’t get me wrong, but that’s not a 14-2 team anymore. They look more like 10-7, 11-6 to me,” one opposing GM cautioned, suggesting the margin for error has tightened. Dan Campbell doesn’t need the reminder. His emotional postgame warning after the Lions’ near-miss two seasons ago still echoes: “I told those guys, this may have been our only shot... And it’s gonna be twice as hard to get back to this. next year”. True to his words, the seasons since has indeed been an uphill battle. Yet, as the Lions charge toward what they hope will be a different ending, they do so by embracing the pressure rather than fearing it. This team has learned how to fight through adversity without making excuses, just as Hutchinson vowed. Whether the Lions capitalize on this window or see it close unfulfilled, they have already altered the NFL landscape by making Detroit a contender again. And if the story does end in a Super Bowl celebration, the years of heartache will have been worth it for the Lions and their loyal believers."
        },
        "created_at": "2025-12-05T19:49:07.794948+00:00"
    }
];
