import { SupabaseArticle } from './types';

// Mock data structured exactly like the Supabase response for fallback/testing
export const MOCK_SUPABASE_DATA: SupabaseArticle[] = [
  {
      "id": "c4def10a-6488-47e1-a226-2b5f343f236c",
      "article_key": "lions-superbowl-window",
      "language_code": "de",
      "title": "Am Abgrund zum Ruhm",
      "subtitle": "Die Detroit Lions im Super-Bowl-Fenster",
      "author": "BigSlikTobi",
      "published_at": "2025-12-05",
      "hero_image_url": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_images/2025_12_05_LionsSB16_9.png",
      "audio_file": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/tts/lionsSB_audio.mp3",
    "video_file": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_videos/lionsSB_teaser.mp4",
      "sections": {
          "section_1": "## Keine Tränen, nur Entschlossenheit\n### Nach einer herzzerreißenden Playoff-Pleite weigert sich das Team, den Super-Bowl-Traum aufzugeben.\n\nAls vor zwei Spielzeiten die letzten Sekunden im NFC Championship Game verstrichen waren, stand Defensive End Aidan Hutchinson an der Seitenlinie, den Helm in der Hand und weigerte sich, auch nur eine Träne zu vergießen. Die Lions waren nur eine Halbzeit vom Super Bowl entfernt gewesen, ehe ihr Vorsprung in einer bitteren zweiten Hälfte noch aus den Händen glitt. Nach der bitteren Niederlage im NFC Championship Game teilte Aidan Hutchinson eine Botschaft, die die Entschlossenheit einer ganzen Stadt auf den Punkt brachte: „In Detroit wirst du keine Tränen finden. Wenn du nach Ausreden suchst, wirst du sie aus dem Ford Field nicht hören... So schwer die heutige Niederlage auch war, sie definiert nicht die Kultur der Detroit Lions. Sie ist ein Beleg dafür, wie weit wir gekommen sind und wie weit wir noch gehen können“, erklärte der lokale Publikumsliebling und gelobte, dass dieser Rückschlag ihren Hunger nur noch anfachen würde. Jetzt, in Woche 13 der Saison 2025, brennt dieser Hunger heißer denn je. Aus Herzschmerz ist Hoffnung geworden und die Lions sind fest entschlossen, eine Titelchance zu ergreifen, die in Detroit lange Zeit undenkbar schien.",
          "section_2": "## Hochleistungs-Offensive treibt Detroit voran\n### Quarterback Jared Goff und eine vielseitige Angriffsreihe haben die Lions zu einer der explosivsten Offenses der Liga gemacht.\n\nNach jener Playoff-Enttäuschung setzten die Lions alles auf ihre Offense, um bald wieder angreifen zu können. Quarterback Jared Goff, der einst von den Rams aussortiert wurde, hat sich in Detroit zu einem selbstbewussten Anführer einer Hochleistungs-Offensive gemausert. Umgeben von jungen Waffen erzielte Goff im vergangenen Jahr Karriere-Bestmarken in der Effizienz, er leistete sich kaum Ballverluste und glänzte sogar, wenn die Gegner Druck ausübten. Die Lions wurden das erste Team der NFL-Geschichte, das gleichzeitig zwei Running Backs (der dynamische Rookie Jahmyr Gibbs und Power-Back David Montgomery) und zwei Wide Receiver (Pro-Bowler Amon-Ra St. Brown und der pfeilschnelle Jameson Williams) mit jeweils über 1.000 Total Yards from Scrimmage (Rushing + Receiving) in einer Saison. Zusammen mit dem aufstrebenden Tight End Sam LaPorta erklärt das, warum Detroits Angriff zu den explosivsten der Liga zählt. Trotz des Abschieds des gefeierten Offensivkoordinators Ben Johnson nach der letzten Saison setzte Head Coach Dan Campbell auf Kontinuität, er holte den erfahrenen Assistenten John Morton zurück, um das etablierte System intakt zu halten. Das Resultat? Eine Unit, die weiterhin Woche für Woche zu den punktstärksten der NFL gehört. Für Goff ist die Verwandlung in Detroit auch eine persönliche Mission. „Seit meiner Ankunft war das mein Ziel... Jetzt an dem Punkt zu stehen und die Chance zu haben, den Super Bowl zu gewinnen, ist wirklich aufregend. Wir haben aber noch einen langen Weg vor uns“, betonte Goff nüchtern. Diese bodenständige Zuversicht durchdringt die gesamte Offense, eine Offense, die glaubt, gegen jeden Gegner punkten zu können, und auf genau dieses Selbstvertrauen wird Detroit setzen, wenn die Einsätze noch höher werden.",
          "section_3": "## Eine Abwehr zeigt Zähne\n### Detroits einstige Achillesferse präsentiert sich 2025 bissig und gesund.\n\nDie Verteidigung war lange Zeit der wunde Punkt der Lions, doch nun schlägt das Pendel mit Wucht in die andere Richtung aus. Vergangene Saison wurde die Lions-Defense vom Verletzungspech heimgesucht, bis Dezember standen 21 Spieler der Lions auf Injured Reserve, ligaweit Spitze in der Saison 2024. Dennoch hatte Defensive Coordinator Aaron Glenn eine aggressive junge Einheit geformt; zur Saisonmitte 2024 gehörte die Lions-Defense zu den besten der Liga, bevor die Verletzungsserie sie ausbremste. Dieses Jahr beginnt ein neuer Abschnitt unter dem frischen Defensive Coordinator Kelvin Sheppard, und mit den zurückkehrenden Leistungsträgern hat die Einheit ihr bissiges Selbstvertrauen wiedergefunden. Die Wirkung der wieder genesenen Stars ist sofort spürbar. Edge Rusher Aidan Hutchinson, nach seinem Beinbruch vollständig genesen, knüpft direkt an seine alte Dominanz an, in den ersten fünf Spielen der vergangenen Saison verbuchte er 7,5 Sacks, mehr als jeder andere Verteidiger der NFL in diesem Zeitraum. An seiner Seite stehen nun weitere Talente wie Linebacker Jack Campbell und Safety Kerby Joseph, und die Lions-Defense strotzt wieder vor Energie und Biss. Ein frühes Saison-Highlight zeigte eindrucksvoll den Wandel dieser Abwehr: In einem Monday-Night-Duell in Baltimore jagte Detroits Defense Ravens-Quarterback Lamar Jackson über das Feld und brachte ihn siebenmal zu Boden. Ein Statement-Sieg, der deutlich machte, dass man diese Verteidigung nicht länger auf die leichte Schulter nehmen darf. Die Spieler treten mit dem Selbstverständnis an, dass ihre Unit an vorderster Front den Ton angibt. Mit einem wieder zur Höchstform auflaufenden Hutchinson und zahlreichen Rückkehrern aus der Verletzungspause ist Detroits Defense längst kein Schwachpunkt mehr, sie hat sich zu einem treibenden Faktor für einen möglichen Titel run entwickelt.",
          "section_4": "## Geformt durch Härte: Der Campbell-Faktor\n### Dan Campbell hat den Lions eine Kultur des Kampfgeists verpasst, doch der Verlust seiner Top-Assistenten stellt das Team auf eine harte Probe.\n\nVon dem Moment an, als Dan Campbell 2021 seinen Posten als Head Coach antrat und vollmundig davon sprach, Gegnern „die Kniescheiben abzubeißen“, war klar: Unter ihm würden die Lions durch Härte und Herz definiert werden. In den vergangenen Jahren hat sich diese Philosophie voll ausgezahlt. Aus dem einstigen Prügelknaben der Liga ist ein Team geworden, das in den letzten drei Saisons 36 Siege bei 15 Niederlagen verzeichnete. Die viertbeste Bilanz der NFL,  und bis an die Spitze der NFC North geklettert ist. „Sie haben eine echte Kultur von Mut und Toughness installiert“, bemerkte ein Scout eines Rivalen, der feststellte, dass sich Campbells Mannschaft „jedes Jahr weiter gesteigert hat“. Die feurige, ansteckende Energie des Coaches hat eine Franchise elektrisiert, die früher meist das Schlimmste befürchten musste. Jetzt steht Campbell vor seiner vielleicht größten Bewährungsprobe als Anführer. In dieser Offseason wurden ihm gleich beide brillanten Koordinatoren weggeschnappt: Offensiv-Guru Ben Johnson ging als Head Coach zu den Bears nach Chicago, Defensivchef Aaron Glenn übernahm die New York Jets. Ein solcher Aderlass im Trainerstab ist in der NFL kaum gesehen, und so mancher Insider fragte sich, ob die zuvor über sich hinausgewachsenen Lions ohne diese Masterminds an Fahrt verlieren könnten. „Beide Typen auf einmal zu verlieren, das ist kein Spaß... Ich denke, sie werden zurückfallen“, urteilte ein skeptischer gegnerischer General Manager. Campbell reagierte darauf, indem er auf die von ihm geschaffene Kultur vertraute: Er beförderte den erst 34-jährigen Linebacker-Coach Kelvin Sheppard zum Defensive Coordinator und holte den langjährigen Assistenten John Morton als Offensive Coordinator zurück nach Detroit. Keiner der beiden verfügt auf NFL-Niveau über Erfahrung als Spielzugchef, ein Wagnis, das ligaweit für hochgezogene Augenbrauen sorgte. Doch innerhalb des Lions-Teamgefüges herrscht die Überzeugung, dass Campbells Vision und das gelegte Fundament die Mannschaft auch durch diesen Umbruch tragen werden. Wie der Coach seinen Spielern stets einschärft: Der Standard in Detroit ändert sich nicht, nur weil sich einige Gesichter ändern.",
          "section_5": "## Jetzt oder nie? Das Fenster der Gelegenheit\n### Das Super-Bowl-Fenster der Lions steht offen.\n\nWie Detroit diese Chance nutzt, wird über das Erbe der leidgeprüften Franchise entscheiden. Nach Jahrzehnten der Erfolglosigkeit steht das Meisterschaftsfenster der Lions endlich offen, doch niemand weiß, wie lange.Vor der Saison 2023/24 hatte Detroit in der Super-Bowl-Ära nur ein einziges Playoff-Spiel gewonnen und ist noch nie im NFL-Endspiel gestanden. Die Fans in der Motor City haben Generationen der Enttäuschung durchlitten und warten seit Ewigkeiten auf ein Team wie dieses. Entsprechend tragen die Lions 2025 sowohl die Hoffnungen einer Stadt als auch die Bürde hoher Erwartungen auf ihren Schultern. Auf dem Papier ist die Gelegenheit zum Greifen nah: Der Kader ist gespickt mit jungen Stars im besten Alter, und das Selbstvertrauen aus zwei Playoff-Jahren in Folge hat einen neuen Anspruch in Detroit etabliert. Doch die NFL ist dafür bekannt, dass sich ein Fenster schneller schließen kann, als es sich öffnet. Einige Experten fragen sich bereits, ob die Erfolgswelle der Lions nach dem Verlust wichtiger Trainer ihren Höhepunkt nicht schon überschritten hat. „Es ist immer noch ein gutes Team… aber das ist kein 14-2-Team mehr. Sie sehen für mich eher aus wie 10-7 oder 11-6“, gab ein rivalisierender GM zu Protokoll, was bedeutet, dass der Spielraum für Fehler kleiner geworden ist. Dan Campbell braucht diese Mahnungen eigentlich nicht. Seine eigene emotionale Warnung nach dem knapp verpassten großen Wurf vor zwei Jahren hallt bis heute nach: „Ich sagte den Jungs: Das hier war vielleicht unsere einzige Chance... und es wird doppelt so schwer, nächstes Jahr wieder an diesem Punkt zu stehen.” Und tatsächlich ist seither jede Saison noch mühsamer geworden. Dennoch stürmen die Lions nun mit dem festen Willen voran, dass dieses Mal ein anderes Ende geschrieben wird, sie nehmen den Druck an, anstatt ihn zu fürchten. Dieses Team hat gelernt, sich durch Widrigkeiten zu kämpfen, ohne nach Ausreden zu suchen, genau wie Hutchinson es versprochen hatte. Ob die Lions dieses Fenster nutzen oder zusehen müssen, wie es sich schließt, ohne dass der große Triumph gelingt: Sie haben die NFL bereits jetzt verändert, indem sie Detroit wieder zu einem ernstzunehmenden Titelanwärter gemacht haben. Und sollte diese Geschichte tatsächlich in einer Super-Bowl-Feier gipfeln, wären all die Jahre des Herzschmerzes für die Lions und ihre treuen Anhänger mehr als wettgemacht."
      },
      "created_at": "2025-12-05T19:53:38.562577+00:00"
  },
  {
      "id": "ae891814-cb5a-43a4-b7d7-1264927c2f98",
      "article_key": "lions-superbowl-window",
      "language_code": "en",
      "title": "Roaring at the Brink",
      "subtitle": "Lions Chase a Super Bowl Dream",
      "author": "BigSlikTobi",
      "published_at": "2025-12-05",
      "hero_image_url": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_images/2025_12_05_LionsSB16_9.png",
      "audio_file": "",
    "video_file": "https://yqtiuzhedkfacwgormhn.supabase.co/storage/v1/object/public/deep_dive_videos/lionsSB_teaser.mp4",
      "sections": {
          "section_1": "## No Tears, Only Determination\n### After a gut-wrenching playoff defeat, the Lions refuse to let their Super Bowl dreams slip away. \n\nAs the final seconds ticked away in the NFC Championship Game two seasons ago, Detroit Lions defensive end Aidan Hutchinson stood on the sideline, helmet in hand, refusing to let any tears fall. The Lions had been just one half of football away from a Super Bowl berth, only to see their lead slip away in a crushing second-half collapse. In the quiet locker room afterward, Hutchinson said little publicly. But days later, he posted a message that captured the mood in Detroit: ‘You won’t find tears in Detroit. If you want excuses, you won’t hear them coming from Ford Field...  As hard as today’s loss was, it is not a definition of the Detroit Lions culture. It’s a testament to how far we have come and how far we can go,” the hometown star declared, vowing that the setback would only fuel their hunger. Now, as Week 13 of 2025 arrives, that hunger burns hotter than ever. The Lions have transformed heartbreak into hope, determined to seize a championship opportunity that once seemed unimaginable in Detroit.",
          "section_2": "## High-Octane Offense Ignites Detroit’s Charge\n### Jared Goff and a balanced arsenal have made the Lions one of the league’s most explosive offensive teams.\n\nAfter that playoff heartbreak, the Lions doubled down on their offense to ensure they’d be back in the fight. Quarterback Jared Goff, once cast off by the Rams, has flourished into a confident leader in Detroit’s high-octane attack. Surrounded by a young arsenal of playmakers, Goff posted career-best efficiency last season, cutting down on mistakes and even thriving when opponents brought pressure. The Lions became the first team in NFL history with two running backs (dynamic rookie Jahmyr Gibbs and bruising veteran David Montgomery) and two wide receivers (Pro Bowler Amon-Ra St. Brown and the speedy Jameson Williams) each gaining over 1,000 yards from scrimmage in the same year. Add in emerging star tight end Sam LaPorta, and it’s easy to see why Detroit’s offense has been among the league’s most explosive. Even with beloved offensive coordinator Ben Johnson departing after last season, coach Dan Campbell opted for continuity, rehiring veteran assistant John Morton to keep the scheme and terminology familiar. The result? A unit that still ranks near the top of the NFL in point production each week. For Goff, the transformation in Detroit is deeply personal. “Since I got here, it’s been a goal of mine to be where we’re standing right now and have a chance to win the Super Bowl is pretty exciting. We’ve got a long way to go,” Goff said, keeping the team’s recent success in perspective. That measured confidence trickles down through an offense that believes it can score on anyone, a belief the Lions will lean on as the stakes rise.",
          "section_3": "## A Defense with Bite\n### Detroit’s once-maligned defense is stepping up, with stars returning and a mantra of tenacity fueling its resurgence.\n\nDefense used to be the Lions’ sore spot, but that narrative is changing with a vengeance. Last season, Detroit’s defense was ravaged by injuries, 21 different players landed on injured reserve, making it the most snake-bit unit in the league in 2024. Despite the setbacks, coordinator Aaron Glenn had built a ferocious young group. By midseason they ranked among the NFL’s best before the injury bug hit. This year brings a fresh start under new defensive coordinator Kelvin Sheppard, and a renewed focus on aggressiveness and fundamentals. The impact of having their stars back healthy has been immediate. Edge rusher Aidan Hutchinson, fully recovered from a broken leg, has resumed his dominant form, he opened last season with 7.5 sacks in just five games, more than any defender in the NFL over that span. Now he’s flanked by emerging playmakers like linebacker Jack Campbell and safety Kerby Joseph, giving Detroit a youthful, swarming defense with real bite. One early-season performance encapsulated the unit’s rise: on a Monday night in Baltimore, the Lions defense chased Ravens quarterback Lamar Jackson all over the field, sacking him seven times in a statement win that announced Detroit’s defensive arrival. Playing with a swagger instilled by Sheppard and the veterans, this unit now approaches each game intent on being the tip of the spear. With Hutchinson leading by example and so many reinforcements returning, the Lions’ defense no longer looks like a liability, it looks like a catalyst for a championship run.",
          "section_4": "## Guided by Grit: The Campbell Factor\n### Head coach Dan Campbell’s culture change has transformed the Lions, but losing his top assistants will test Detroit’s resilience.\n\nFrom the moment Dan Campbell arrived as head coach in 2021 talking about biting off kneecaps, he made one thing clear: his Lions would be defined by toughness and heart. Over the past few seasons, that ethos has taken hold. Detroit went from league doormat to a 36-15 record over the past three seasons, the fourth-best mark in the NFL, rising to the top of the NFC North behind a legion of blossoming young talent. “They’ve installed a legitimate culture of grit and toughness,” observed one rival scout, noting how Campbell’s team “ascended every single year” under his guidance. The coach’s fiery, infectious energy has galvanized a franchise that used to expect the worst. Now Campbell faces perhaps his greatest test as a leader. This past offseason, both of his brilliant coordinators were hired away to head coaching jobs, offensive guru Ben Johnson to Chicago and defensive chief Aaron Glenn to the New York Jets. Such a dual brain drain is almost unheard of, and even some NFL insiders wondered if the overachieving Lions might “fall off” without those minds on staff. Campbell’s response was to trust the culture he built: he promoted 34-year-old linebackers coach Kelvin Sheppard to run the defense and brought back veteran assistant John Morton to call plays on offense. Sheppard has never been a coordinator at this level, while Morton returns for his second stint as an NFL offensive coordinator after previously running the Jets’ offense in 2017, a gamble that raised eyebrows around the league. But inside the Lions’ facility, there’s faith that Campbell’s vision and the foundation he’s laid will carry them through the transition. As he often reminds his players, the standard in Detroit doesn’t change just because the faces do.",
          "section_5": "## Now or Never? The Window of Opportunity\n### Detroit’s championship window is open and what comes next will define a long-suffering franchise’s legacy.\n\nAfter decades of futility, the Lions’ window for a championship is finally open but nobody knows for how long. In the Super Bowl era, Detroit has won only a single playoff game, never even reaching the sport’s biggest stage. Fans in Detroit have endured generations of disappointment, waiting for a team like this to believe in. That’s why the 2025 Lions carry both the hopes of a city and the weight of expectation. On paper, the opportunity is there: the roster is stacked with young stars in their prime, and the confidence gained from back-to-back playoff campaigns has set a new standard. But the NFL has a way of slamming windows shut in the blink of an eye. Rival executives have openly wondered if Detroit’s run might already have peaked, especially after the loss of its key coaches. “It’s still a good team, don’t get me wrong, but that’s not a 14-2 team anymore. They look more like 10-7, 11-6 to me,” one opposing GM cautioned, suggesting the margin for error has tightened. Dan Campbell doesn’t need the reminder. His emotional postgame warning after the Lions’ near-miss two seasons ago still echoes: “I told those guys, this may have been our only shot... And it’s gonna be twice as hard to get back to this point next year”. True to his words, the seasons since has indeed been an uphill battle. Yet, as the Lions charge toward what they hope will be a different ending, they do so by embracing the pressure rather than fearing it. This team has learned how to fight through adversity without making excuses, just as Hutchinson vowed. Whether the Lions capitalize on this window or see it close unfulfilled, they have already altered the NFL landscape by making Detroit a contender again. And if the story does end in a Super Bowl celebration, the years of heartache will have been worth it for the Lions and their loyal believers."
      },
      "created_at": "2025-12-05T19:49:07.794948+00:00"
  }
];